# Site settings
title: "rhaz.es"
email: "rhazes at rhaz period es"
description: "web log of media artist rhaze spell. documenting projects, writing, and experiments around technology | media art | software | science | fun. "
baseurl: ""
url: "http://rhaz.es"
include:
 - _pages
 - _work


# Build settings
markdown: kramdown
kramdown:
 input: GFM 
permalink: none
relative_permalinks: false
exclude: 
 - Procfile
 - README
 - sublime.project
 - neat
 - bourbon

# Set the Sass partials directory, as we're using @imports
sass:
 sass_dir: _sass
 style: :expanded

