# Site settings
title: "rhaz.es"
email: "rhazes at rhaz period es"
description: " HMMMM!!! processing, digital art, graphics, UCLA, Duke"
baseurl: ""
url: "http://rhaz.es"
include:
 - _pages
 - _portfolio


# Build settings
markdown: kramdown
kramdown:
 input: GFM 
permalink: none
relative_permalinks: false
exclude: 
 - sass
 - Procfile
 - README
